# Generated by Django 3.1.2 on 2022-03-13 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, verbose_name="Client's phone number")),
                ('provider_code', models.CharField(max_length=3, verbose_name="Clients's provider identificator")),
                ('time_zone', models.CharField(max_length=30, verbose_name="Client's timezone")),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name="Mailing's text")),
                ('start_mailing_date', models.DateTimeField(verbose_name='When start mailing')),
                ('stop_mailing_date', models.DateTimeField(verbose_name='When stop mailing')),
                ('count_of_sended_messages', models.IntegerField(null=True, verbose_name='Count of sended messages')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name="Tag's name")),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(verbose_name='The message was sent')),
                ('status', models.BooleanField(verbose_name='Status of message')),
                ('clients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name="Client's id")),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailing.mailing', verbose_name="Mailing's id")),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='mailing.tag', verbose_name="Tag's name"),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mailing.Tag', verbose_name="Client's tags"),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
