# Generated by Django 3.1.2 on 2022-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='count_of_sended_messages',
            field=models.IntegerField(default=0, null=True, verbose_name='Count of sended messages'),
        ),
    ]
