# Generated by Django 3.1.2 on 2022-03-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20220314_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='clients_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tag', to='mailing.client', verbose_name="Client's id"),
        ),
    ]
